spring.application.name=bus-ticket-api



spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.username=system
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=${PORT:8080}

payos.client-id=ec05d039-ff2a-40e4-a29a-3bcd6ca169e6  
payos.api-key=62ef3207-0f1c-40b9-9dfb-db285dcb9ebb
payos.checksum-key=a236b56788a04a1ee131712c1abbc921b9987a752387d4ec8fafb687a44be69f

app.frontend-url=http://127.0.0.1:5501/frontend/bus-ticket-web
app.jwt.secret=bus-ticket-dev-jwt-secret-bus-ticket-dev-jwt-secret
app.jwt.expiration-ms=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=khanhnguhuhu@gmail.com
spring.mail.password=idid jemy vbdn tnfp